CREATE TABLE Company(
	Id bigint IDENTITY(1,1) NOT NULL,
	UserId bigint NOT NULL,
	Description nvarchar(20) NOT NULL,
	Location nvarchar(20) NOT NULL
 CONSTRAINT PK_Company PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE Company WITH NOCHECK ADD  CONSTRAINT [FK_Company_User] FOREIGN KEY([UserId])
REFERENCES User([Id])
GO

ALTER TABLE Company CHECK CONSTRAINT [FK_Company_User]
GO


CREATE NONCLUSTERED INDEX [IX_FK_Company_UserId] ON Company
(
	UserId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



