CREATE TABLE User(
	Id bigint IDENTITY(1,1) NOT NULL,
	Email nvarchar(20) NOT NULL,
	Name nvarchar(20) NOT NULL,
	Password nvarchar(20) NULL,
	RegistrationDate datetime2(7),
 CONSTRAINT PK_User PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

